### ISSUE TITLE
cache未加载

### ISSUE THREAD

**Issue by Ankali-Aylina** [koishijs/koishi-plugin-enka#1]
![image](https://user-images.githubusercontent.com/109135335/220513537-e90a42de-a6d3-4d05-aac3-abf259f5b54a.png)
我已经加载了所需的cache服务，并且修改为了5分钟，但是他还是显示未加载

**Comment by Lipraty** [comment]
这个 cache 经过研究不是一个必须的，目前 0.1.8 已经修改为可选依赖，可以更新后使用哦~
